name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    strategy:
      matrix:
        python-version: [3.9, 3.10.6]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt  # If you have any requirements
        
    - name: Run tests
      run: python test/test.py