name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.6.15, 3.7, 3.8, 3.9, 3.10.6, 3.11]
      os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any requirements
        
    - name: Run tests
      run: python test/test.py